### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by cjones26** [jigneshkhatri/primeng-treenode-preselect#1]
To utilize this, don't we need to totally replace the "p-tree" component as well, being it imports TreeNode?  I'm figuring we would need to replace the import in "p-tree" with these custom files.

Thanks!

**Comment by jigneshkhatri** [comment]
The example I had shown, is its usage only. You have to write that code in the component where you want to use <p-tree>. In my example, treeNodes.component is the component where I have used <p-tree>. Nothing needs to be replaced, just use that code which I have provided and you are done.

**Comment by cjones26** [comment]
Oh, after looking a bit closer I understand--I was a bit sleepy earlier and did not realize how this operated.  Feel free to close the issue, I will give it a shot tomorrow!

Thanks!

**Comment by jigneshkhatri** [comment]
Yeah. Thanks.
